import { useEffect, useState } from "react";
import { Redirect, router } from "expo-router";
import { Alert, View, Text, StyleSheet, Pressable, ActivityIndicator } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { Screen } from "@/components/Screen";
import { ProgressBar } from "@/components/ProgressBar";
import { ANSWERS, DIMENSIONS, QUESTIONS } from "@/data/questions";
import { COLORS, RADIUS, SHADOW } from "@/constants/theme";
import { useAuth } from "@/context/AuthContext";
import { saveAnswer, startQuestionnaire, submitQuestionnaire } from "@/services/questionnaire";

export default function QuestionnaireScreen(){
 const {token,user}=useAuth(); const[current,setCurrent]=useState(0);const[answers,setAnswers]=useState<Record<string,number>>({});const[assessmentId,setAssessmentId]=useState<string|null>(null);const[busy,setBusy]=useState(false);const[loading,setLoading]=useState(true);const question=QUESTIONS[current];const selected=answers[question.id];const dimension=DIMENSIONS[question.dimension];
 useEffect(()=>{if(!token||!user)return;startQuestionnaire(token,user.id).then(a=>setAssessmentId(a.id)).catch(e=>{console.error("QUESTIONNAIRE START ERROR",e);Alert.alert("Questionnaire",e instanceof Error?e.message:"Impossible de démarrer l'évaluation.")}).finally(()=>setLoading(false))},[token,user]);
 const choose=(value:number)=>setAnswers(a=>({...a,[question.id]:value}));
 const next=async()=>{if(selected===undefined||!token||!assessmentId)return;setBusy(true);try{await saveAnswer(token,assessmentId,question.id,selected);if(current===QUESTIONS.length-1){await submitQuestionnaire(token,assessmentId);Alert.alert("Évaluation terminée","Votre bilan est maintenant disponible.",[{text:"Voir mes résultats",onPress:()=>router.replace("/(tabs)/resultats")}]);}else setCurrent(c=>c+1);}catch(e){Alert.alert("Enregistrement",e instanceof Error?e.message:"Une erreur est survenue.")}finally{setBusy(false)}};
 if(!token||!user)return <Redirect href="/welcome"/>;
 if(loading)return <Screen><View style={{paddingTop:70,alignItems:"center"}}><ActivityIndicator color={COLORS.link}/><Text style={{color:COLORS.textMuted,marginTop:12}}>Préparation de votre évaluation…</Text></View></Screen>;
 return <Screen><View style={styles.top}><Pressable onPress={()=>router.back()} style={styles.back}><Ionicons name="arrow-back" size={20} color={COLORS.depth}/></Pressable><Text style={styles.counter}>{current+1} / {QUESTIONS.length}</Text><Text style={[styles.dimension,{color:dimension.color}]}>{dimension.label}</Text></View><ProgressBar value={((current+(selected?1:0))/QUESTIONS.length)*100} color={dimension.color}/><View style={styles.dots}>{Object.entries(DIMENSIONS).map(([key,d])=><View key={key} style={[styles.dot,{backgroundColor:question.dimension===key?d.color:COLORS.border}]}/>)}</View><View style={styles.card}><View style={[styles.badge,{backgroundColor:dimension.color}]}><Text style={styles.badgeText}>{question.dimension}</Text></View><Text style={styles.question}>{question.text}</Text><Text style={styles.helper}>Choisissez la réponse qui vous ressemble le plus.</Text><View style={styles.answers}>{ANSWERS.map(a=><Pressable key={a.value} onPress={()=>choose(a.value)} style={[styles.answer,selected===a.value&&{borderColor:dimension.color,backgroundColor:COLORS.serenity}]}><View style={[styles.radio,selected===a.value&&{borderColor:dimension.color}]}>{selected===a.value&&<View style={[styles.radioInner,{backgroundColor:dimension.color}]}/>}</View><Text style={styles.answerText}>{a.label}</Text></Pressable>)}</View></View><View style={styles.bottom}><Text style={styles.answered}>{Object.keys(answers).length} réponse{Object.keys(answers).length>1?"s":""} enregistrée{Object.keys(answers).length>1?"s":""}</Text><Pressable onPress={next} disabled={selected===undefined||busy} style={[styles.next,(selected===undefined||busy)&&styles.nextDisabled]}><Text style={styles.nextText}>{busy?"Enregistrement…":current===QUESTIONS.length-1?"Terminer":"Continuer"}</Text><Ionicons name="arrow-forward" size={18} color={COLORS.white}/></Pressable></View></Screen>
}
const styles=StyleSheet.create({top:{flexDirection:"row",alignItems:"center",marginBottom:12,gap:10},back:{width:40,height:40,borderRadius:20,backgroundColor:COLORS.white,alignItems:"center",justifyContent:"center",...SHADOW.card},counter:{color:COLORS.textMuted,fontSize:12,fontWeight:"700"},dimension:{marginLeft:"auto" as any,fontSize:11,fontWeight:"800",maxWidth:"48%"},dots:{flexDirection:"row",justifyContent:"space-between",paddingHorizontal:2,marginTop:9,marginBottom:18},dot:{width:7,height:7,borderRadius:7},card:{backgroundColor:COLORS.white,borderRadius:RADIUS.lg,padding:20,...SHADOW.card},badge:{alignSelf:"flex-start",borderRadius:RADIUS.pill,paddingHorizontal:9,paddingVertical:6},badgeText:{color:COLORS.white,fontSize:9,fontWeight:"800",letterSpacing:.6},question:{color:COLORS.depth,fontSize:24,lineHeight:31,fontWeight:"800",marginTop:17},helper:{color:COLORS.textMuted,fontSize:12,lineHeight:18,marginTop:9,marginBottom:20},answers:{gap:9},answer:{borderWidth:1.2,borderColor:COLORS.border,borderRadius:RADIUS.md,padding:13,flexDirection:"row",alignItems:"center",gap:11},radio:{width:22,height:22,borderRadius:11,borderWidth:2,borderColor:"#A6B8B6",alignItems:"center",justifyContent:"center"},radioInner:{width:10,height:10,borderRadius:5},answerText:{flex:1,color:COLORS.depth,fontSize:12,lineHeight:17,fontWeight:"600"},bottom:{marginTop:16,flexDirection:"row",alignItems:"center",gap:10},answered:{flex:1,color:COLORS.textMuted,fontSize:10},next:{backgroundColor:COLORS.link,borderRadius:RADIUS.pill,paddingVertical:13,paddingHorizontal:17,flexDirection:"row",alignItems:"center",gap:7},nextDisabled:{opacity:.45},nextText:{color:COLORS.white,fontSize:12,fontWeight:"800"}});
