import { router } from "expo-router";
import { useState } from "react";
import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { Screen } from "@/components/Screen";
import { BrandMark } from "@/components/BrandMark";
import { COLORS, RADIUS, SHADOW } from "@/constants/theme";
import { useAuth } from "@/context/AuthContext";
import { saveConsent } from "@/services/onboarding";
export default function ConsentScreen(){const{token,refresh}=useAuth();const[a,setA]=useState(false),[b,setB]=useState(false),[c,setC]=useState(false),[busy,setBusy]=useState(false);const submit=async()=>{if(!token||!a||!b)return;setBusy(true);try{await saveConsent(token,{consentInformation:a,consentResearch:b,consentParticipation:c});await refresh();router.replace("/onboarding/demographics")}catch(e){Alert.alert("Impossible",e instanceof Error?e.message:"Réessayez.")}finally{setBusy(false)}};return <Screen><BrandMark/><View style={styles.header}><View style={styles.icon}><Ionicons name="shield-checkmark-outline" size={25} color={COLORS.link}/></View><View style={{flex:1}}><Text style={styles.title}>Bienvenue</Text><Text style={styles.subtitle}>Avant de commencer, prenons un moment pour vous expliquer le parcours.</Text></View></View><View style={styles.card}><Text style={styles.heading}>L'évaluation IQRH</Text><Text style={styles.text}>Le questionnaire aide à comprendre la qualité de vos relations dans les sphères personnelle, familiale, sociale, professionnelle et affective.</Text><Text style={styles.text}>Vos réponses servent à établir votre profil relationnel, calculer votre IQRH et proposer des recommandations personnalisées.</Text><Text style={styles.text}>La participation est volontaire. Vous pouvez interrompre le parcours à tout moment.</Text><Text style={styles.text}>Les informations recueillies sont confidentielles et traitées conformément à la réglementation applicable aux données personnelles.</Text></View><Check checked={a} onPress={()=>setA(!a)} required text="J'ai pris connaissance des informations ci-dessus."/><Check checked={b} onPress={()=>setB(!b)} required text="J'accepte que mes réponses soient utilisées de manière anonyme à des fins statistiques et scientifiques."/><Check checked={c} onPress={()=>setC(!c)} text="Je consens à participer à cette étude."/><Pressable style={[styles.button,(!a||!b||busy)&&styles.disabled]} disabled={!a||!b||busy} onPress={submit}><Text style={styles.buttonText}>{busy?"Enregistrement…":"Continuer vers mon profil"}</Text><Ionicons name="arrow-forward" size={18} color={COLORS.white}/></Pressable></Screen>}
function Check({checked,onPress,required,text}:{checked:boolean;onPress:()=>void;required?:boolean;text:string}){return <Pressable onPress={onPress} style={styles.check}><View style={[styles.box,checked&&styles.boxChecked]}>{checked&&<Ionicons name="checkmark" size={14} color={COLORS.white}/>}</View><Text style={styles.checkText}>{text}{required&&<Text style={{color:COLORS.energy}}> *</Text>}</Text></Pressable>}
const styles=StyleSheet.create({header:{flexDirection:"row",gap:13,alignItems:"center",marginVertical:24},icon:{width:50,height:50,borderRadius:16,backgroundColor:COLORS.serenity,alignItems:"center",justifyContent:"center"},title:{color:COLORS.depth,fontSize:26,fontWeight:"800"},subtitle:{color:COLORS.textMuted,fontSize:12,lineHeight:18,marginTop:4},card:{backgroundColor:COLORS.white,borderRadius:RADIUS.lg,padding:20,...SHADOW.card,marginBottom:17},heading:{color:COLORS.depth,fontSize:17,fontWeight:"800",marginBottom:9},text:{color:COLORS.textMuted,fontSize:12,lineHeight:19,marginBottom:10},check:{flexDirection:"row",gap:12,alignItems:"flex-start",paddingVertical:10},box:{width:23,height:23,borderRadius:7,borderWidth:2,borderColor:COLORS.border,alignItems:"center",justifyContent:"center",marginTop:1},boxChecked:{backgroundColor:COLORS.link,borderColor:COLORS.link},checkText:{flex:1,color:COLORS.depth,fontSize:12,lineHeight:18},button:{marginTop:15,backgroundColor:COLORS.link,borderRadius:RADIUS.pill,paddingVertical:15,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:8},disabled:{opacity:.4},buttonText:{color:COLORS.white,fontSize:14,fontWeight:"800"}})
