import { router } from "expo-router";
import { View, Text, StyleSheet, Pressable, Alert } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { Screen } from "@/components/Screen";
import { BrandMark } from "@/components/BrandMark";
import { COLORS, RADIUS, SHADOW } from "@/constants/theme";
import { useAuth } from "@/context/AuthContext";
export default function ProfilScreen(){const{user,logout,deleteAccount}=useAuth();const initials=`${user?.firstName?.[0]||""}${user?.lastName?.[0]||""}`.toUpperCase();const confirmDelete=()=>Alert.alert("Supprimer définitivement mon compte","Cette action est définitive. Votre compte et les données associées seront supprimés. Voulez-vous continuer ?",[{text:"Annuler",style:"cancel"},{text:"Supprimer définitivement",style:"destructive",onPress:async()=>{try{await deleteAccount();router.replace("/welcome")}catch(error){Alert.alert("Suppression impossible",error instanceof Error?error.message:"Réessayez plus tard.")}}}]);return <Screen><BrandMark/><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>{initials}</Text></View><Text style={styles.name}>{user?.firstName} {user?.lastName}</Text><Text style={styles.sub}>{user?.email}</Text></View>{[["person-outline","Informations personnelles"],["shield-checkmark-outline","Confidentialité & consentement"],["help-circle-outline","Aide & support"]].map(([icon,label])=><Pressable style={styles.row} key={label as string}><View style={styles.icon}><Ionicons name={icon as any} size={19} color={COLORS.link}/></View><Text style={styles.rowText}>{label}</Text><Ionicons name="chevron-forward" size={19} color="#789096"/></Pressable>)}<Pressable style={[styles.row,{marginTop:8}]} onPress={()=>Alert.alert("Déconnexion","Voulez-vous vous déconnecter ?",[{text:"Annuler",style:"cancel"},{text:"Se déconnecter",style:"destructive",onPress:async()=>{await logout();router.replace("/welcome")}}])}><View style={[styles.icon,{backgroundColor:"#FCE8E8"}]}><Ionicons name="log-out-outline" size={19} color={COLORS.danger}/></View><Text style={[styles.rowText,{color:COLORS.danger}]}>Se déconnecter</Text></Pressable><Pressable style={styles.deleteRow} onPress={confirmDelete}><Ionicons name="trash-outline" size={18} color={COLORS.danger}/><Text style={styles.deleteText}>Supprimer définitivement mon compte</Text></Pressable><View style={styles.footer}><Text style={styles.footerTitle}>Link Office</Text><Text style={styles.footerText}>Laboratoire du lien humain</Text><Text style={styles.version}>Version mobile • iOS & Android</Text></View></Screen>}
const styles=StyleSheet.create({profile:{alignItems:"center",paddingVertical:25},avatar:{width:78,height:78,borderRadius:39,backgroundColor:COLORS.serenity,alignItems:"center",justifyContent:"center",marginBottom:12},avatarText:{color:COLORS.depth,fontSize:23,fontWeight:"800"},name:{color:COLORS.depth,fontSize:22,fontWeight:"800"},sub:{color:COLORS.textMuted,fontSize:11,marginTop:4},row:{backgroundColor:COLORS.white,borderRadius:RADIUS.md,padding:14,flexDirection:"row",alignItems:"center",gap:12,marginBottom:9,...SHADOW.card},icon:{width:38,height:38,borderRadius:19,backgroundColor:COLORS.serenity,alignItems:"center",justifyContent:"center"},rowText:{flex:1,color:COLORS.depth,fontSize:13,fontWeight:"700"},deleteRow:{flexDirection:"row",alignItems:"center",justifyContent:"center",gap:8,paddingVertical:15,marginTop:12},deleteText:{color:COLORS.danger,fontSize:12,fontWeight:"800"},footer:{alignItems:"center",marginTop:28,paddingTop:20,borderTopWidth:1,borderTopColor:COLORS.border},footerTitle:{color:COLORS.depth,fontSize:14,fontWeight:"800"},footerText:{color:COLORS.textMuted,fontSize:11,marginTop:3},version:{color:"#789096",fontSize:10,marginTop:12}});
