import { PrismaClient, Dimension, QuestionKind } from "@prisma/client";
const prisma = new PrismaClient();
const reference = [
  ["Q1","SOCIAL","Je peux compter sur plusieurs personnes si je rencontre une difficulté importante."],["Q2","SOCIAL","Je me sens entouré(e) au quotidien."],["Q3","SOCIAL","Je participe régulièrement à des activités ou à des échanges avec d'autres personnes."],["Q4","SOCIAL","Je me sens accepté(e) tel(le) que je suis par les personnes qui m'entourent."],["Q5","SOCIAL","Lorsque je traverse une période difficile, je sais vers qui me tourner."],["Q6","SOCIAL","Je crée facilement de nouvelles relations."],
  ["Q7","AFFECTIVE","Je me sens aimé(e) et apprécié(e)."],["Q8","AFFECTIVE","Je peux exprimer facilement mes émotions auprès des personnes en qui j'ai confiance."],["Q9","AFFECTIVE","Je reçois le soutien affectif dont j'ai besoin lorsque je traverse une période difficile."],["Q10","AFFECTIVE","Je me sens émotionnellement en sécurité dans mes relations importantes."],["Q11","AFFECTIVE","Je peux être pleinement moi-même avec les personnes qui comptent pour moi."],["Q12","AFFECTIVE","Je reçois régulièrement des marques d'affection, de bienveillance ou d'attention."],
  ["Q13","SENTIMENTAL","Je suis satisfait(e) de ma vie sentimentale actuelle."],["Q14","SENTIMENTAL","Ma situation sentimentale actuelle correspond à ce que je souhaite aujourd'hui."],["Q15","SENTIMENTAL","Je peux exprimer librement mes besoins affectifs."],["Q16","SENTIMENTAL","Je vis, ou j'espère vivre, des relations affectives épanouissantes."],["Q17","SENTIMENTAL","Je parviens à gérer sereinement les difficultés liées à ma vie sentimentale."],["Q18","SENTIMENTAL","J'ai confiance dans mon avenir sentimental."],
  ["Q19","PROFESSIONAL","Je me sens reconnu(e) dans l'activité qui occupe aujourd'hui la plus grande place dans mon quotidien."],["Q20","PROFESSIONAL","Je peux compter sur les personnes avec lesquelles j'interagis dans cette activité."],["Q21","PROFESSIONAL","Je peux exprimer librement mes idées et mon point de vue."],["Q22","PROFESSIONAL","Les relations que j'entretiens dans cette activité sont globalement positives et respectueuses."],["Q23","PROFESSIONAL","Je me sens utile à travers cette activité."],["Q24","PROFESSIONAL","Cette activité contribue positivement à mon équilibre de vie."],
  ["Q25","SELF","Je me sens en accord avec mes valeurs."],["Q26","SELF","J'ai le sentiment que ma vie a du sens."],["Q27","SELF","Je prends régulièrement du temps pour prendre soin de moi."],["Q28","SELF","Je suis satisfait(e) de l'équilibre entre les différentes sphères de ma vie."],["Q29","SELF","Je me projette avec confiance dans les prochaines années."],["Q30","SELF","Globalement, je suis satisfait(e) de ma qualité de vie relationnelle."],
] as const;
const modules = [
  ["Célibataire","comprendre les opportunités, les freins et les ressources dans la vie sentimentale.",["Les occasions de rencontrer de nouvelles personnes me semblent suffisantes.","Mon entourage respecte ma situation sentimentale actuelle.","Les outils actuels (applications, réseaux, activités…) répondent à mes attentes pour faire des rencontres.","Mon célibat me permet aujourd'hui de développer d'autres projets de vie importants.","Je sais clairement quel type de relation je souhaite construire."]],
  ["En couple","identifier les leviers favorisant l'équilibre du couple.",["Notre organisation quotidienne laisse une place suffisante à notre relation.","Nous parvenons à préserver des moments de qualité malgré nos contraintes.","Les responsabilités extérieures ont peu d'impact sur notre relation.","Nous savons demander de l'aide lorsque notre couple traverse une difficulté.","Nous partageons une vision commune de notre avenir."]],
  ["Parent","identifier les facteurs influençant l'équilibre entre parentalité et vie personnelle.",["Les responsabilités parentales limitent parfois mes relations sociales.","Je dispose de relais lorsque j'en ai besoin.","Je culpabilise lorsque je prends du temps pour moi.","Mon entourage reconnaît les responsabilités liées à mon rôle de parent.","Je parviens à préserver des espaces qui me sont entièrement consacrés."]],
  ["Famille monoparentale","identifier les contraintes spécifiques et les ressources disponibles.",["Je peux compter sur un réseau d'entraide fiable.","Les contraintes d'organisation limitent mes possibilités de créer ou maintenir des relations.","Les démarches administratives ou logistiques représentent une charge importante.","Je trouve facilement du soutien lorsque je rencontre une difficulté.","Je parviens à conserver des projets personnels malgré mes responsabilités."]],
  ["Entrepreneur","comprendre les facteurs relationnels liés à l'entrepreneuriat.",["Je prends seul(e) la majorité des décisions importantes.","Mon entourage comprend les contraintes liées à mon activité.","Il m'est difficile de déconnecter mentalement de mon activité.","Je reporte régulièrement des moments personnels en raison de mes responsabilités professionnelles.","Je participe régulièrement à des réseaux ou communautés de dirigeants."]],
  ["Manager","identifier les leviers relationnels du management.",["Je dispose d'espaces pour échanger sur les difficultés liées à mon rôle de manager.","Les responsabilités managériales génèrent une charge émotionnelle importante.","Je dispose de suffisamment de temps pour accompagner mon équipe.","Je me sens soutenu(e) lorsque je dois gérer une situation complexe.","Je bénéficie de formations ou d'outils adaptés à mes responsabilités."]],
  ["Étudiant","comprendre les facteurs favorisant l'intégration et la réussite.",["Il est facile de créer des liens dans mon environnement d'études.","Je participe à des activités favorisant les rencontres.","Je connais les ressources disponibles lorsque je rencontre une difficulté.","Les exigences de mes études limitent parfois ma vie sociale.","Je me sens encouragé(e) dans mon parcours."]],
  ["Retraité","identifier les facteurs favorisant le maintien du lien social.",["Je participe régulièrement à des activités favorisant les rencontres.","Je découvre encore de nouveaux centres d'intérêt.","Les changements liés à la retraite ont modifié mon réseau relationnel.","Je trouve facilement des occasions de partager des moments avec d'autres.","Je me sens acteur de cette nouvelle étape de vie."]],
  ["Aidant familial","mesurer la charge relationnelle spécifique des aidants.",["Je connais les dispositifs pouvant m'aider dans mon rôle d'aidant.","J'accepte facilement de demander de l'aide.","Mon rôle d'aidant réduit le temps consacré à mes autres relations.","Je dispose de temps de répit réguliers.","Mon entourage comprend les contraintes liées à mon rôle."]],
  ["Personne vivant seule","distinguer le choix de vie de l'isolement subi.",["Le fait de vivre seul(e) correspond à un choix qui me convient.","Mon logement favorise les visites et les échanges.","Je prends facilement l'initiative de proposer des activités.","Je participe régulièrement à la vie locale ou associative.","Je me sens connecté(e) à mon environnement de proximité."]],
  ["Demandeur d'emploi","identifier les impacts relationnels de la recherche d'emploi.",["Ma recherche d'emploi me permet de conserver un rythme de vie structuré.","Je continue à développer mon réseau professionnel.","Je connais les dispositifs pouvant m'accompagner.","Ma situation actuelle limite certaines de mes activités sociales.","Je continue à développer mes compétences malgré cette période."]],
  ["Création d'entreprise","comprendre les enjeux relationnels des premières années d'entrepreneuriat.",["Je suis accompagné(e) dans le développement de mon entreprise.","Je bénéficie d'un réseau facilitant mon développement.","Les responsabilités liées au lancement de mon activité influencent ma vie personnelle.","Je trouve facilement des interlocuteurs lorsque je rencontre une difficulté.","Je prends le temps de célébrer les réussites de mon projet."]],
  ["Divorce / séparation récente","identifier les ressources mobilisées dans la reconstruction.",["Je bénéficie d'un entourage sur lequel je peux m'appuyer.","Cette période m'a amené(e) à développer de nouvelles relations.","Les aspects administratifs ou financiers pèsent encore sur mon équilibre.","Je retrouve progressivement des repères dans ma vie quotidienne.","Je me sens libre de construire un nouveau projet de vie."]],
  ["Deuil récent","comprendre les ressources disponibles pendant le processus de deuil.",["Je peux parler librement de la personne disparue si je le souhaite.","Mon entourage respecte mon rythme dans cette épreuve.","Je connais les ressources d'accompagnement disponibles si j'en ressens le besoin.","Je retrouve progressivement des activités qui me procurent du plaisir.","Je parviens à maintenir des liens avec les personnes importantes pour moi."]],
] as const;
async function main() { await prisma.question.deleteMany(); await prisma.adaptiveModule.deleteMany(); await prisma.question.createMany({ data: reference.map(([id, dimension, text], index) => ({ id, text, position: index + 1, kind: QuestionKind.REFERENCE, dimension: dimension as Dimension })) }); for (const [index, [triggerSituation, objective, questions]] of modules.entries()) { await prisma.adaptiveModule.create({ data: { id: `MOD${index + 1}`, triggerSituation, title: `Module ${triggerSituation}`, objective, position: index + 1, questions: { create: questions.map((text, questionIndex) => ({ id: `MOD${index + 1}_Q${questionIndex + 1}`, position: questionIndex + 1, text })) } } }); } await prisma.user.upsert({ where: { email: "demo@linkoffice.fr" }, create: { email: "demo@linkoffice.fr", firstName: "Camille", lastName: "Demo" }, update: {} }); }
main().finally(() => prisma.$disconnect());
