"use client";

import { useEffect, useState } from "react";
import { PolarAngleAxis, PolarGrid, Radar, RadarChart, ResponsiveContainer } from "recharts";

type LibraryItem = { id: string; title: string; data: Record<string, unknown> };
type Result = {
  globalScore: number; weather: string; weatherText: string; primaryProfile: string; secondaryProfile: string; profileSummary: string;
  balanceIndex: number; priorityDimension: string; strengths: string[]; watchpoints: string[];
  socialScore: number; affectiveScore: number; sentimentalScore: number; professionalScore: number; selfScore: number;
  icr: { score: number; level: string; interpretation: string; riskFactors: string[]; protectiveFactors: string[]; dominantNeeds: string[] } | null;
  profile: { signature: string; primaryConfidence: number; secondaryConfidence: number } | null;
  prescription: { title: string; summary: string; items: Array<{ id: string; kind: string; rationale: string; libraryItem: LibraryItem }> } | null;
};

const labels = ["Relations sociales", "Relations affectives", "Vie sentimentale", "Vie professionnelle et engagement", "Relation à soi et au sens"];

export default function Results({ params }: { params: Promise<{ userId: string }> }) {
  const [result, setResult] = useState<Result | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { params.then(async ({ userId }) => { const response = await fetch(`/api/resultats/${userId}`); const body = await response.json() as Result & { error?: string }; if (!response.ok) setError(body.error ?? "Résultats indisponibles."); else setResult(body); }); }, [params]);
  if (error) return <main className="grid min-h-screen place-items-center bg-slate-50 p-6 text-slate-700">{error}</main>;
  if (!result) return <main className="grid min-h-screen place-items-center bg-slate-50">Chargement de vos résultats…</main>;
  const scores = [result.socialScore, result.affectiveScore, result.sentimentalScore, result.professionalScore, result.selfScore];
  const radar = labels.map((dimension, index) => ({ dimension, score: scores[index] }));
  return <main className="min-h-screen bg-slate-50 py-10"><section className="mx-auto max-w-6xl px-6">
    <header><p className="font-semibold tracking-wide text-indigo-600">LINK OFFICE · VOTRE BILAN IQRH</p><h1 className="mt-2 text-4xl font-bold text-slate-950">Votre qualité relationnelle, aujourd&apos;hui</h1><p className="mt-3 max-w-3xl text-slate-600">Cette restitution présente vos résultats IQRH, votre indice de complexité relationnelle et les premières actions de votre ordonnance relationnelle.</p></header>
    <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_1.25fr]"><article className="rounded-3xl bg-indigo-600 p-8 text-white"><p className="text-indigo-100">Votre score IQRH</p><p className="mt-3 text-6xl font-bold">{Math.round(result.globalScore)}<span className="text-2xl">/100</span></p><p className="mt-6 text-xl font-semibold">{result.weather}</p><p className="mt-2 text-indigo-100">{result.weatherText}</p><p className="mt-5 text-sm text-indigo-100">Indice d&apos;équilibre relationnel : {Math.round(result.balanceIndex)}/100</p></article><article className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="font-semibold text-slate-900">Votre radar relationnel</h2><div className="h-80"><ResponsiveContainer><RadarChart data={radar}><PolarGrid /><PolarAngleAxis dataKey="dimension" tick={{ fontSize: 11 }} /><Radar dataKey="score" stroke="#4f46e5" fill="#4f46e5" fillOpacity={0.28} /></RadarChart></ResponsiveContainer></div></article></div>
    <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{radar.map((item) => <article key={item.dimension} className="rounded-2xl bg-white p-4 shadow-sm"><p className="text-sm text-slate-500">{item.dimension}</p><p className="mt-2 text-3xl font-bold">{Math.round(item.score)}</p><div className="mt-3 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-indigo-500" style={{ width: `${item.score}%` }} /></div></article>)}</section>
    <section className="mt-6 grid gap-6 lg:grid-cols-2"><article className="rounded-3xl bg-white p-6 shadow-sm"><p className="text-sm font-semibold text-indigo-600">VOTRE PROFIL RELATIONNEL</p><h2 className="mt-2 text-2xl font-bold">{result.primaryProfile}</h2><p className="mt-3 text-slate-600">{result.profileSummary}</p><p className="mt-5 text-sm font-semibold text-indigo-600">PROFIL SECONDAIRE</p><p className="mt-1 text-lg font-medium">{result.secondaryProfile}</p>{result.profile && <p className="mt-4 text-sm text-slate-500">Confiance d&apos;identification : {result.profile.primaryConfidence}/100</p>}</article><article className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Votre dimension prioritaire</h2><p className="mt-3 text-slate-600">{result.priorityDimension}</p><p className="mt-3 text-sm text-slate-500">Elle guide les actions proposées dans votre ordonnance relationnelle.</p></article><ListCard title="Vos 3 principales forces" items={result.strengths} /><ListCard title="Vos 3 principaux points de vigilance" items={result.watchpoints} /></section>
    {result.icr && <section className="mt-6 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><article className="rounded-3xl bg-slate-900 p-7 text-white"><p className="text-sm font-semibold tracking-wide text-indigo-200">ICR · INDICE DE COMPLEXITÉ RELATIONNELLE</p><p className="mt-4 text-5xl font-bold">{result.icr.score}<span className="text-xl">/100</span></p><p className="mt-3 text-lg font-semibold">{result.icr.level}</p><p className="mt-2 text-sm text-slate-300">{result.icr.interpretation}</p></article><article className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Vos repères de contexte</h2><MiniList title="Facteurs de risque" items={result.icr.riskFactors} /><MiniList title="Facteurs protecteurs" items={result.icr.protectiveFactors} /><MiniList title="Besoins dominants" items={result.icr.dominantNeeds} /></article></section>}
    <section className="mt-6 rounded-3xl bg-white p-6 shadow-sm"><p className="text-sm font-semibold text-indigo-600">ORDONNANCE RELATIONNELLE</p><h2 className="mt-2 text-2xl font-bold">{result.prescription?.title ?? "Préparation de votre ordonnance"}</h2><p className="mt-2 text-slate-600">{result.prescription?.summary ?? "Votre ordonnance sera disponible dès que la bibliothèque aura été synchronisée."}</p><div className="mt-5 grid gap-4 lg:grid-cols-2">{result.prescription?.items.map((item) => <article key={item.id} className="rounded-2xl border border-slate-200 p-5"><p className="text-xs font-semibold text-indigo-600">{item.kind === "MICRO_CHALLENGE" ? "MICRO-DÉFI" : "RECOMMANDATION"}</p><h3 className="mt-2 font-bold text-slate-900">{item.libraryItem.title}</h3><p className="mt-2 text-sm text-slate-600">{item.rationale}</p></article>)}</div></section>
    <section className="mt-6 grid gap-6 lg:grid-cols-3"><Placeholder title="Votre espace IRIS" text="Cette zone est réservée à l’intégration du futur accompagnement conversationnel." /><Placeholder title="Votre parcours de prescription" text="Le suivi de progression et les réévaluations seront branchés sur cette restitution." /><Placeholder title="Votre binôme relationnel" text="Cette zone est réservée au futur module communautaire." /></section>
  </section></main>;
}

function ListCard({ title, items }: { title: string; items: string[] }) { return <article className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">{title}</h2><ol className="mt-4 space-y-3">{items.map((item, index) => <li key={item} className="flex gap-3"><span className="font-semibold text-indigo-600">0{index + 1}</span><span className="text-slate-600">{item}</span></li>)}</ol></article>; }
function MiniList({ title, items }: { title: string; items: string[] }) { return <div className="mt-4"><h3 className="text-sm font-semibold text-slate-700">{title}</h3><p className="mt-1 text-sm text-slate-500">{items.length ? items.join(" · ") : "Aucun élément identifié."}</p></div>; }
function Placeholder({ title, text }: { title: string; text: string }) { return <article className="rounded-3xl border border-dashed border-indigo-200 bg-indigo-50/40 p-6"><h2 className="font-bold text-slate-900">{title}</h2><p className="mt-3 text-sm text-slate-600">{text}</p></article>; }
