import { router } from "expo-router";
import { useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { BrandMark } from "@/components/BrandMark";
import { Screen } from "@/components/Screen";
import { COLORS, RADIUS, SHADOW } from "@/constants/theme";
import { useAuth } from "@/context/AuthContext";
export default function RegisterScreen(){
 const {register}=useAuth(); const [form,setForm]=useState({prenom:"",nom:"",email:"",password:"",codeAccess:""}); const [busy,setBusy]=useState(false); const set=(k:keyof typeof form)=>(v:string)=>setForm(x=>({...x,[k]:v}));
 const submit=async()=>{if(!form.prenom||!form.nom||!form.email||!form.password)return Alert.alert("Champs requis","Complétez les informations demandées.");if(form.password.length<8||!/[A-Z]/.test(form.password)||!/[0-9]/.test(form.password))return Alert.alert("Mot de passe","Utilisez au moins 8 caractères, une majuscule et un chiffre.");setBusy(true);try{await register(form);router.replace("/");}catch(e){Alert.alert("Inscription impossible",e instanceof Error?e.message:"Réessayez.")}finally{setBusy(false)}};
 return <Screen><BrandMark/><View style={styles.header}><Text style={styles.title}>Créez votre compte</Text><Text style={styles.subtitle}>Votre parcours commence par quelques informations simples.</Text></View><View style={styles.card}><Field label="Prénom" value={form.prenom} set={set("prenom")} placeholder="Marie"/><Field label="Nom" value={form.nom} set={set("nom")} placeholder="Dupont"/><Field label="Email" value={form.email} set={set("email")} placeholder="vous@exemple.com" keyboardType="email-address"/><Field label="Mot de passe" value={form.password} set={set("password")} placeholder="8 caractères minimum" secure/><Field label="Code d'accès (facultatif)" value={form.codeAccess} set={set("codeAccess")} placeholder="Fourni par votre organisation"/><Pressable style={[styles.button,busy&&{opacity:.55}]} onPress={submit} disabled={busy}><Text style={styles.buttonText}>{busy?"Création…":"Créer mon compte"}</Text><Ionicons name="arrow-forward" size={18} color={COLORS.white}/></Pressable></View><Text style={styles.legal}>En créant votre compte, vous pourrez accéder à votre évaluation et à vos résultats personnels.</Text><Pressable onPress={()=>router.push("/auth/login")}><Text style={styles.switch}>Déjà un compte ? <Text style={{color:COLORS.link,fontWeight:"800"}}>Se connecter</Text></Text></Pressable></Screen>
}
function Field({label,value,set,placeholder,secure,keyboardType}:{label:string;value:string;set:(v:string)=>void;placeholder:string;secure?:boolean;keyboardType?:any}){return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={styles.input} value={value} onChangeText={set} placeholder={placeholder} placeholderTextColor="#9AAEAC" secureTextEntry={secure} keyboardType={keyboardType}/></View>}
const styles=StyleSheet.create({header:{marginVertical:26},title:{color:COLORS.depth,fontSize:29,fontWeight:"800"},subtitle:{color:COLORS.textMuted,fontSize:13,lineHeight:20,marginTop:8},card:{backgroundColor:COLORS.white,borderRadius:RADIUS.lg,padding:20,...SHADOW.card},field:{marginBottom:14},label:{color:COLORS.depth,fontSize:12,fontWeight:"800",marginBottom:7},input:{height:50,borderWidth:1,borderColor:COLORS.border,borderRadius:RADIUS.md,backgroundColor:"#FBFCFA",paddingHorizontal:13,color:COLORS.depth,fontSize:13},button:{marginTop:3,backgroundColor:COLORS.link,borderRadius:RADIUS.pill,paddingVertical:15,flexDirection:"row",justifyContent:"center",alignItems:"center",gap:8},buttonText:{color:COLORS.white,fontSize:14,fontWeight:"800"},legal:{color:COLORS.textMuted,fontSize:10,lineHeight:15,textAlign:"center",marginTop:15},switch:{textAlign:"center",color:COLORS.textMuted,fontSize:12,marginTop:17}}
);
